package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Footballer;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface FootballerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOTBALLER
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    int deleteByPrimaryKey(Integer idf);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOTBALLER
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    int insert(Footballer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOTBALLER
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    Footballer selectByPrimaryKey(Integer idf);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOTBALLER
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    List<Footballer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOOTBALLER
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    int updateByPrimaryKey(Footballer record);
}