package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Stadium;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface StadiumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STADIUM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STADIUM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    int insert(Stadium record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STADIUM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    Stadium selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STADIUM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    List<Stadium> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STADIUM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    int updateByPrimaryKey(Stadium record);
}