package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.TeamStadium;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface TeamStadiumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM_STADIUM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM_STADIUM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    int insert(TeamStadium record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM_STADIUM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    TeamStadium selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM_STADIUM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    List<TeamStadium> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM_STADIUM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    int updateByPrimaryKey(TeamStadium record);
}