package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Team;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface TeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    int insert(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    Team selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    List<Team> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TEAM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    int updateByPrimaryKey(Team record);
}