package lt.vu.mybatis.model;

public class Footballer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FOOTBALLER.IDF
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    private Integer idf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FOOTBALLER.NAME
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FOOTBALLER.NUMBER
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.FOOTBALLER.TEAM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    private Integer team;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FOOTBALLER.IDF
     *
     * @return the value of PUBLIC.FOOTBALLER.IDF
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public Integer getIdf() {
        return idf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FOOTBALLER.IDF
     *
     * @param idf the value for PUBLIC.FOOTBALLER.IDF
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public void setIdf(Integer idf) {
        this.idf = idf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FOOTBALLER.NAME
     *
     * @return the value of PUBLIC.FOOTBALLER.NAME
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FOOTBALLER.NAME
     *
     * @param name the value for PUBLIC.FOOTBALLER.NAME
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FOOTBALLER.NUMBER
     *
     * @return the value of PUBLIC.FOOTBALLER.NUMBER
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FOOTBALLER.NUMBER
     *
     * @param number the value for PUBLIC.FOOTBALLER.NUMBER
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.FOOTBALLER.TEAM
     *
     * @return the value of PUBLIC.FOOTBALLER.TEAM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public Integer getTeam() {
        return team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.FOOTBALLER.TEAM
     *
     * @param team the value for PUBLIC.FOOTBALLER.TEAM
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public void setTeam(Integer team) {
        this.team = team;
    }
}