package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

public class Stadium {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STADIUM.ID
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STADIUM.NAME
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STADIUM.CAPACITY
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    private Integer capacity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STADIUM.ID
     *
     * @return the value of PUBLIC.STADIUM.ID
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */

    @Setter
    @Getter
    private List<Team> teams;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STADIUM.ID
     *
     * @param id the value for PUBLIC.STADIUM.ID
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STADIUM.NAME
     *
     * @return the value of PUBLIC.STADIUM.NAME
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STADIUM.NAME
     *
     * @param name the value for PUBLIC.STADIUM.NAME
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STADIUM.CAPACITY
     *
     * @return the value of PUBLIC.STADIUM.CAPACITY
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STADIUM.CAPACITY
     *
     * @param capacity the value for PUBLIC.STADIUM.CAPACITY
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }
}