package lt.vu.mybatis.model;

public class TeamStadium {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM_STADIUM.ID
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM_STADIUM.TEAMID
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    private Integer teamid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TEAM_STADIUM.STADIUMID
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    private Integer stadiumid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM_STADIUM.ID
     *
     * @return the value of PUBLIC.TEAM_STADIUM.ID
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM_STADIUM.ID
     *
     * @param id the value for PUBLIC.TEAM_STADIUM.ID
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM_STADIUM.TEAMID
     *
     * @return the value of PUBLIC.TEAM_STADIUM.TEAMID
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public Integer getTeamid() {
        return teamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM_STADIUM.TEAMID
     *
     * @param teamid the value for PUBLIC.TEAM_STADIUM.TEAMID
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public void setTeamid(Integer teamid) {
        this.teamid = teamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TEAM_STADIUM.STADIUMID
     *
     * @return the value of PUBLIC.TEAM_STADIUM.STADIUMID
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public Integer getStadiumid() {
        return stadiumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TEAM_STADIUM.STADIUMID
     *
     * @param stadiumid the value for PUBLIC.TEAM_STADIUM.STADIUMID
     *
     * @mbg.generated Tue Apr 25 15:48:58 EEST 2017
     */
    public void setStadiumid(Integer stadiumid) {
        this.stadiumid = stadiumid;
    }
}